// ============================================================
// DATA.JS — Données fictives des produits RePhone
// ============================================================

const products = [
  {
    id: 1,
    name: "iPhone 14 Pro",
    brand: "Apple",
    grade: "A",
    storage: "256 Go",
    color: "Noir Spatial",
    price: 699,
    originalPrice: 1229,
    battery: 92,
    image: null, // On utilisera un SVG généré
    emoji: "📱",
    color_code: "#1a1a1e",
    specs: ["Puce A16 Bionic", "Écran 6.1\" Super Retina XDR", "Triple caméra 48 MP", "5G", "Face ID"],
    description: "L'iPhone 14 Pro reconditionné Grade A est en état quasi-neuf. Aucune trace visible d'usure. Batterie à 92% de sa capacité d'origine. Fourni avec câble USB-C et chargeur.",
    inStock: true
  },
  {
    id: 2,
    name: "Samsung Galaxy S23",
    brand: "Samsung",
    grade: "A",
    storage: "128 Go",
    color: "Crème",
    price: 489,
    originalPrice: 899,
    battery: 88,
    image: null,
    emoji: "📱",
    color_code: "#f5f0e8",
    specs: ["Snapdragon 8 Gen 2", "Écran 6.1\" Dynamic AMOLED", "Triple caméra 50 MP", "5G", "IP68"],
    description: "Samsung Galaxy S23 reconditionné Grade A. Très légères micro-rayures invisibles à l'œil. Batterie en excellente forme. Débloqué tout opérateur.",
    inStock: true
  },
  {
    id: 3,
    name: "Google Pixel 8",
    brand: "Google",
    grade: "A",
    storage: "128 Go",
    color: "Hazel",
    price: 449,
    originalPrice: 799,
    battery: 90,
    image: null,
    emoji: "📱",
    color_code: "#6b7c5a",
    specs: ["Puce Google Tensor G3", "Écran 6.2\" OLED", "Caméra 50 MP avec IA", "5G", "7 ans de mises à jour"],
    description: "Pixel 8 reconditionné Grade A avec toutes les fonctionnalités IA de Google. Batterie > 90%. État impeccable. Android pur garanti 7 ans.",
    inStock: true
  },
  {
    id: 4,
    name: "iPhone 13",
    brand: "Apple",
    grade: "B",
    storage: "128 Go",
    color: "Minuit",
    price: 399,
    originalPrice: 909,
    battery: 83,
    image: null,
    emoji: "📱",
    color_code: "#1c2033",
    specs: ["Puce A15 Bionic", "Écran 6.1\" Super Retina XDR", "Double caméra 12 MP", "5G", "Face ID"],
    description: "iPhone 13 Grade B avec légères rayures sur la coque, invisibles avec une coque de protection. Écran parfait. Batterie à 83%. Toujours performant en 2025.",
    inStock: true
  },
  {
    id: 5,
    name: "Samsung Galaxy A54",
    brand: "Samsung",
    grade: "B",
    storage: "256 Go",
    color: "Violet",
    price: 249,
    originalPrice: 499,
    battery: 85,
    image: null,
    emoji: "📱",
    color_code: "#6b4fa0",
    specs: ["Exynos 1380", "Écran 6.4\" Super AMOLED", "Triple caméra 50 MP", "5G", "IP67"],
    description: "Le meilleur rapport qualité/prix Samsung reconditionné. Grade B avec légères traces d'usage. Batterie solide. Idéal pour les utilisateurs polyvalents.",
    inStock: true
  },
  {
    id: 6,
    name: "iPhone 12",
    brand: "Apple",
    grade: "C",
    storage: "64 Go",
    color: "Rouge",
    price: 269,
    originalPrice: 809,
    battery: 78,
    image: null,
    emoji: "📱",
    color_code: "#c41e3a",
    specs: ["Puce A14 Bionic", "Écran 6.1\" Super Retina XDR", "Double caméra 12 MP", "5G", "Face ID"],
    description: "iPhone 12 Grade C avec rayures visibles sur la coque. Écran sans fissures. Batterie à 78% (remplacement recommandé à terme). Parfait pour ceux qui veulent un iPhone 5G abordable.",
    inStock: true
  },
  {
    id: 7,
    name: "Samsung Galaxy S22 Ultra",
    brand: "Samsung",
    grade: "A",
    storage: "256 Go",
    color: "Blanc Phantom",
    price: 599,
    originalPrice: 1259,
    battery: 91,
    image: null,
    emoji: "📱",
    color_code: "#f0f0f0",
    specs: ["Snapdragon 8 Gen 1", "Écran 6.8\" Dynamic AMOLED", "Quad caméra 108 MP", "S Pen intégré", "IP68"],
    description: "Le flagship ultimate de Samsung reconditionné Grade A. Avec S Pen intégré, zoom 100x et écran de 6.8\". État quasi-neuf, batterie > 91%.",
    inStock: false
  },
  {
    id: 8,
    name: "Google Pixel 7a",
    brand: "Google",
    grade: "B",
    storage: "128 Go",
    color: "Charbon",
    price: 319,
    originalPrice: 549,
    battery: 82,
    image: null,
    emoji: "📱",
    color_code: "#2e2e2e",
    specs: ["Puce Google Tensor G2", "Écran 6.1\" OLED", "Caméra 64 MP", "5G", "Charge sans fil"],
    description: "Pixel 7a reconditionné Grade B. Idéal pour ceux qui veulent l'expérience Pixel pure à prix réduit. Légères traces d'usage, fonctionnement parfait.",
    inStock: true
  },
  {
    id: 9,
    name: "iPhone 14",
    brand: "Apple",
    grade: "B",
    storage: "128 Go",
    color: "Bleu",
    price: 499,
    originalPrice: 1019,
    battery: 86,
    image: null,
    emoji: "📱",
    color_code: "#4a7fa5",
    specs: ["Puce A15 Bionic", "Écran 6.1\" Super Retina XDR", "Double caméra 12 MP", "5G", "Mode Action vidéo"],
    description: "iPhone 14 Grade B en bleu. Légères micro-rayures sur la coque. Écran parfait. Batterie à 86%. Détection d'accident et SOS urgence inclus.",
    inStock: true
  },
  {
    id: 10,
    name: "Samsung Galaxy S21",
    brand: "Samsung",
    grade: "C",
    storage: "128 Go",
    color: "Fantôme Gris",
    price: 219,
    originalPrice: 869,
    battery: 76,
    image: null,
    emoji: "📱",
    color_code: "#888899",
    specs: ["Exynos 2100", "Écran 6.2\" Dynamic AMOLED", "Triple caméra 64 MP", "5G", "IP68"],
    description: "Galaxy S21 Grade C à prix mini. Rayures visibles mais étanchéité IP68 intacte. Batterie à 76%. Pour ceux qui veulent un flagship 5G au meilleur prix.",
    inStock: true
  },
  {
    id: 11,
    name: "iPhone 15",
    brand: "Apple",
    grade: "A",
    storage: "256 Go",
    color: "Rose",
    price: 749,
    originalPrice: 1129,
    battery: 97,
    image: null,
    emoji: "📱",
    color_code: "#f2b8c6",
    specs: ["Puce A16 Bionic", "Écran 6.1\" Super Retina XDR", "Caméra 48 MP", "USB-C", "Dynamic Island"],
    description: "iPhone 15 quasi-neuf Grade A, première génération avec USB-C et Dynamic Island. Batterie à 97%. Le modèle le plus récent de notre catalogue.",
    inStock: true
  },
  {
    id: 12,
    name: "Google Pixel 6",
    brand: "Google",
    grade: "C",
    storage: "128 Go",
    color: "Stormy Black",
    price: 189,
    originalPrice: 649,
    battery: 74,
    image: null,
    emoji: "📱",
    color_code: "#1a1a2e",
    specs: ["Puce Google Tensor", "Écran 6.4\" OLED", "Caméra 50 MP", "5G", "Charge sans fil"],
    description: "Pixel 6 Grade C, le premier Pixel avec puce Tensor de Google. Rayures sur la coque mais écran nickel. Batterie à 74%. Pour les amateurs de Pixel à petit budget.",
    inStock: true
  }
];

// Avis fictifs
const reviews = [
  { author: "Marie L.", rating: 5, text: "Livraison rapide, téléphone en parfait état. Exactement ce qui était annoncé. Je recommande !", date: "12 mars 2025", product: "iPhone 14 Pro" },
  { author: "Thomas G.", rating: 4, text: "Très bon rapport qualité/prix. Quelques micro-rayures mais rien de visible avec la coque. Batterie au top.", date: "4 mars 2025", product: "Samsung Galaxy S23" },
  { author: "Sophie R.", rating: 5, text: "Mon premier reconditionné et je suis conquise. Vraiment comme neuf, impossible de faire la différence.", date: "28 février 2025", product: "iPhone 15" },
  { author: "Karim B.", rating: 4, text: "Bon produit, bon prix. Seul bémol : le délai de livraison un peu long (5 jours). Mais je suis satisfait.", date: "20 février 2025", product: "Google Pixel 8" },
  { author: "Lucie M.", rating: 5, text: "Service client très réactif. J'avais une question sur la garantie, réponse en 2h. Téléphone parfait.", date: "15 février 2025", product: "Samsung Galaxy A54" },
  { author: "Antoine D.", rating: 3, text: "Grade C un peu en deçà de mes attentes. Les rayures sont plus visibles que je pensais. Fonctionne parfaitement.", date: "10 février 2025", product: "iPhone 12" }
];
